# fly.toml app configuration file generated for red-darkness-5808 on 2023-05-02T21:38:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-darkness-5808"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"
processes = []

[build]

[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
